---
- name: Install nginx
  hosts: test  # Change to your target host or group if necessary
  become: true
  tasks:
    - name: Install Nginx
      ansible.builtin.package:
        name: nginx
        state: latest
